config/routes.rb
Blogger::Application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [:new, :create, :destroy]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments
  has_many :taggings
  has_many :attachments
  has_many :tags, through: :taggings
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
  belongs_to :author

  def tag_list
    self.tags.collect do |tag|
      tag.name
    end.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
    self.tags = new_or_found_tags
  end

end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  belongs_to :article
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :articles, through: :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :require_login, only: [:new, :create, :update, :destroy]
  include ArticlesHelper

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])

    @comment = Comment.new
    @comment.article_id = @article.id
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(articles_params)
    @article.author = current_user
    @article.save
    flash.notice = "Article '#{@article.title}' Created!"
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(articles_params)

    flash.notice = "Article '#{@article.title}' Updated!"

    redirect_to article_path(@article)
  end

  def destroy
    if logged_in? || current_user == @article.author
      @article = Article.find(params[:id])
      @article.destroy
      flash.notice = "Article '#{@article.title}' Destroyed!"
      redirect_to articles_path
    end
  end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController
  def new
  end

  def create

    if login(params[:email], params[:password])

      redirect_back_or_to(articles_path, notice: 'Logged in successfully.')

    else
      flash.notice = "Login failed."
      render action: :new
    end
  end

  def destroy
    logout
    redirect_to(:authors, notice: 'Logged out!')
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  before_filter :zero_authors_or_authenticated, except: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :require_login, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]

    @comment.save

    redirect_to article_path(@comment.article)
  end

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_filter :require_login, only: [:destroy]

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash.notice = "Article '#{@tag.name}' Destroyed!"
    redirect_to tags_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

  def articles_params
    params.require(:article).permit(:title, :body, :tag_list, :image, :author_id)
  end

end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_comment.html.erb
<div class = "comment-group">
  <h4>Comment by <%= comment.author_name %></h4>
  <p class="comment"><%= comment.body %></p>
  <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p>
</div>

app/views/articles/_form.html.erb
<div class = "body">
  <div class = "form-articles">
    <%= form_for(@article, html: {multipart: true}) do |f| %>
      <ul>
        <% @article.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
      <div class = "form-group">
        <%= f.label :title %><br />
        <%= f.text_field :title, class: "form-control", placeholder: "title" %>
      </div>
      <div class = "form-group">
        <%= f.label :body %><br />
        <%= f.text_area :body, placeholder: "Content" %>
      </div>
      <div class = "form-group">
        <%=f.label :tag_list %><br/>
        <%= f.text_area :tag_list, class: "text-tags", placeholder: "Tags" %>
      </div>
      <div class = "form-group">
        <% if @article.image.exists? %>
          <%= image_tag @article.image.url(:medium) %>
        <% end %>
        <%=  f.label :image, "Attach an Image" %><br/>
        <%=  f.file_field :image %>
      </div>
      <p>
        <%= f.submit class: "btn btn-default" %>
      </p>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1 class >All Articles</h1>
<div class = "body">
  <ul>
    <% @articles.each do |article| %>
      <li class= "li-article">
        <%= link_to article.title, article_path(article), class: 'article_title',
        id: "article_#{article.id}"%>
      </li>
    <% end %>
  </ul>
  <div class = "button_article">
    <% if logged_in? %>
      <%= link_to 'Create a new Article', new_article_path, class: "btn btn-default"%>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>
<%= form_for(@article) do |f| %>
  <ul>
  <% @article.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<div class = "body">
  <% if @article.image.exists? %>
    <p><%= image_tag @article.image.url(:medium) %></p>
  <% end %>
  <p><%= @article.body %></p>
  <p>
    Tags:
    <% @article.tags.each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
    <% end %>
  </p>
  <%=  render partial: 'comments/form' %>
  <%= link_to "<< Back to articles List", articles_path, class: "btn btn-default" %>
  <% if logged_in? && current_user == @article.author %>
    <%= link_to "delete", article_path(@article), class: "btn btn-default", method: :delete, data: {confirm: "Really delete the article?"} %>
    <%= link_to "edit", edit_article_path(@article), class: "btn btn-default" %>
  <% end %>
</div>
<% unless @article.comments.count.zero? %>
  <h3 class="h3-comment">Comments (<%= @article.comments.size %>)</h3>
<% end %>
<div class = "body">
  <%= render partial: 'articles/comment', collection: @article.comments %>
</div>

app/views/author_sessions/new.html.erb
<h1>Login</h1>
<div class = "body">
<%= form_tag author_sessions_path, method: :post do %>
  <div class = "form-group">
    <%= label_tag :email%><br />
    <%= text_field_tag :email, nil, class: "form-control", id: "form-class" %>
  </div>
  <div class= "form-group">
    <%= label_tag :password%><br />
    <%= password_field_tag :password, nil, class: "form-control", id: "form-class"%>
  </div>
  <div class="form-group">
    <%= submit_tag "Login", class: "btn btn-default" %>
    <%= link_to 'Back', articles_path, class: "btn btn-default" %>
  </div>
<% end %>
</div>

app/views/authors/_form.html.erb
<div class = "body">
  <%= form_for(@author) do |f| %>
    <% if @author.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

        <ul>
        <% @author.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :username %><br>
      <%= f.text_field :username, class: "form-control", id: "form-class" %>
    </div>
    <div class="form-group">
      <%= f.label :email %><br>
      <%= f.text_field :email, class: "form-control", id: "form-class" %>
    </div>
    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password, class: "form-control", id: "form-class" %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, class: "form-control", id: "form-class" %>
    </div>
    <div class="actions">
      <%= f.submit class: "btn btn-default"%>
    </div>
  <% end %>
</div>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>
<div class = "body">
  <%= link_to 'Show', @author, class: "btn btn-danger" %>
  <%= link_to 'Back', authors_path , class: "btn btn-danger" %>
</div>

app/views/authors/index.html.erb
<h1>Listing Authors</h1>
<div class = "body">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th><span class="glyphicon glyphicon-search" aria-hidden="true"></span></th>
        <th><span class="glyphicon glyphicon-edit" aria-hidden="true"></span></th>
        <th><span class="glyphicon glyphicon-remove" aria-hidden="true"></th>

      </tr>
    </thead>
    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.username %></td>
          <td><%= author.email %></td>
          <td><%= link_to 'Show', author %></td>
          <% if logged_in? && current_user == author %>
            <td><%= link_to 'Edit', edit_author_path(author) %></td>
            <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% else %>
              <td></td>
              <td></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>

  <%= link_to 'New Author', new_author_path, class: "btn btn-default" %>
</div>

app/views/authors/new.html.erb
<h1>New Author</h1>
<%= render 'form' %>
<div class = "body">
  <%= link_to 'Back', authors_path, class: "btn btn-default" %>
</div>

app/views/authors/show.html.erb
<div class = "show-body-author">
  <div class = "body">
    <p>
      <strong>Username:</strong>
      <%= @author.username %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @author.email %>
    </p>

    <%= link_to 'Edit', edit_author_path(@author), class: "btn btn-danger"%>
    <%= link_to 'Back', authors_path, class: "btn btn-danger"%>
  </div>
</div>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>
<%= form_for [@article, @comment] do |f| %>
  <div class = "form-groups">
    <%= f.label :author_name, "Your Name" %><br/>
    <%= f.text_field :author_name, class: "form-control", id: "form-class" %>
  </div>
  <div class = "form-groups">
    <%= f.label :body, "Your Comment" %><br/>
    <%= f.text_field :body, class: "form-control", id: "form-class" %>
  </div>
  <p>
    <%= f.submit class: "btn btn-default" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blogger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-header">
      <%= link_to 'Home', articles_path, class: "navbar-brand"%>
      <button type="button" data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle">Menu</button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Articles', articles_path %></li>
        <li><%= link_to 'Authors', authors_path %></li>
        <li><%= link_to 'Tags', tags_path%></li>
      </ul>
      <p class="navbar-text navbar-right">
        <% if logged_in? %>
          <%= "Logged in as #{current_user.username}" %>
          <%= link_to "(logout)", logout_path  %>
        <% else %>
          Logged out
          <%= link_to "(login)", login_path %>
          <%= link_to "(Sign up)", new_author_path %>
        <% end %>
      </p>
  </nav>
  <div class="container">
    <div class="content">
      <%= yield %>
      <div class = "body">
      <div class="flash">
        <%= flash.notice %>
      </div>
    </div>
    </div>
  </div>
</body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<div class = "body">
  <ul id="tags">
    <% @tags.each do |tag| %>
      <li class= "li-article"><%= link_to tag.name, tag_path(tag), class: 'article_title' %> </li>
    <% end %>
  </ul>
</div>

app/views/tags/show.html.erb
<h1>Articles Tagged with <%= @tag.name %></h1>
<div class = "body">
  <% if logged_in?%>
    <%= link_to "delete tag", tag_path(@tag), class: "btn btn-danger", method: :delete, data: {confirm: "Really delete the article?"} %>
  <% end %>
  <ul>
    <% @tag.articles.each do |article| %>
      <li><%= link_to article.title, article_path(article) %></li>
    <% end %>
  </ul>
</div>